<a href="https://colab.research.google.com/github/sazbi123/Prog2kakushin/blob/main/work2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
#[place[0]][place[1]]==>y*x
import numpy as np
def game(turn):
  kata=4
  row_sum=0
  line_sum=0
  naname_sumr=0
  naname_suml=0
  a=np.ones((kata,kata))
  print('□行□列の順番に入力してください')
  print('左上から1行1列目が始まります')
  #先攻
  if turn=='f':
    print(a)
    while True:
      print('your turn')
      place=[int(input())-1,int(input())-1]
      a[place[0]][place[1]]='0'
      if place[0]==place[1]:
        for xy in range(kata):
          naname_sumr=naname_sumr+a[xy][xy]
      else:
        naname_sumr=-1
      if place[0]+place[1]==kata-1:
        for xym in range(kata):
          naname_suml=naname_suml+a[0+xym][kata-1-xym]
        #naname_suml=a[0][2]+a[1][1]+a[2][0]
      else:
        naname_suml=-1
      for x in range(kata):
        row_sum=row_sum+a[place[0]][x]
      for y in range(kata):
        line_sum=line_sum+a[y][place[1]]
      if line_sum==0 or row_sum==0 or naname_sumr==0 or naname_suml==0:
        print(a)
        print('you win!')
        break
      row_sum=0
      line_sum=0
      naname_sumr=0
      naname_suml=0

      ran=np.random.randint(0,kata,2)
      while True:
        if a[ran[0]][ran[1]]==0 or a[ran[0]][ran[1]]==8:
          ran=np.random.randint(0,kata,2)
        else:
          break
      a[ran[0]][ran[1]]=8
      if ran[0]==ran[1]:
        for xy in range(kata):
          naname_sumr=naname_sumr+a[xy][xy]
      else:
        naname_sumr=-1
      if ran[0]+ran[1]==kata-1:
        for xym in range(kata):
          naname_suml=naname_suml+a[0+xym][kata-1-xym]
        #naname_suml=a[0][2]+a[1][1]+a[2][0]
      else:
        naname_suml=-1
      for x in range(kata):
        row_sum=row_sum+a[ran[0]][x]
      for y in range(kata):
        line_sum=line_sum+a[y][ran[1]]
      if line_sum==kata*8 or row_sum==kata*8 or naname_sumr==kata*8 or naname_sumr==kata*8:
        print(a)
        print('you lose')
        break
      row_sum=0
      line_sum=0
      naname_sumr=0
      naname_suml=0
      print(a)
  #後攻
  elif turn=='s':
    while True:
      ran=np.random.randint(0,kata,2)
      while True:
        if a[ran[0]][ran[1]]==0 or a[ran[0]][ran[1]]==8:
          ran=np.random.randint(0,kata,2)
        else:
          break
      a[ran[0]][ran[1]]=8
      if ran[0]==ran[1]:
        for xy in range(kata):
          naname_sumr=naname_sumr+a[xy][xy]
      else:
        naname_sumr=-1
      if ran[0]+ran[1]==kata-1:
        for xym in range(kata):
          naname_suml=naname_suml+a[0+xym][kata-1-xym]
        #naname_suml=a[0][2]+a[1][1]+a[2][0]
      else:
        naname_suml=-1
      for x in range(kata):
        row_sum=row_sum+a[ran[0]][x]
      for y in range(kata):
        line_sum=line_sum+a[y][ran[1]]
      if line_sum==kata*8 or row_sum==kata*8 or naname_sumr==kata*8 or naname_sumr==kata*8:
        print(a)
        print('you lose')
        break
      row_sum=0
      line_sum=0
      naname_sumr=0
      naname_suml=0
      print(a)

      print('your turn')
      place=[int(input())-1,int(input())-1]
      a[place[0]][place[1]]='0'
      if place[0]==place[1]:
        for xy in range(kata):
          naname_sumr=naname_sumr+a[xy][xy]
      else:
        naname_sumr=-1
      if place[0]+place[1]==kata-1:
        for xym in range(kata):
          naname_suml=naname_suml+a[0+xym][kata-1-xym]
        #naname_suml=a[0][2]+a[1][1]+a[2][0]
      else:
        naname_suml=-1
      for x in range(kata):
        row_sum=row_sum+a[place[0]][x]
      for y in range(kata):
        line_sum=line_sum+a[y][place[1]]
      if line_sum==0 or row_sum==0 or naname_sumr==0 or naname_suml==0:
        print(a)
        print('you win!')
        break
      row_sum=0
      line_sum=0
      naname_sumr=0
      naname_suml=0
f_or_s=input('先攻：f,後攻：s')
game(f_or_s)


先攻：f,後攻：ss
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 8.]
 [1. 1. 1. 1.]]
your turn
2
1
[[1. 8. 1. 1.]
 [0. 1. 1. 1.]
 [1. 1. 1. 8.]
 [1. 1. 1. 1.]]
your turn


KeyboardInterrupt: Interrupted by user