<a href="https://colab.research.google.com/github/sazbi123/Prog2kakushin/blob/main/work2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
#[place[0]][place[1]]==>y*x
import numpy as np
def game(turn):
  row_sum=0
  line_sum=0
  a=np.ones((3,3))
  if turn=='f':

    print(a)
    while True:
      print('your turn')
      place=[int(input()),int(input())]
      a[place[0]][place[1]]='0'
      for x in range(3):
        row_sum=row_sum+a[place[0]][x]
      print(row_sum)
      for y in range(3):
        line_sum=line_sum+a[y][place[1]]
      print(row_sum)
      if line_sum==0 or row_sum==0:
        print('you win!')
        break
      row_sum=0
      line_sum=0
      print(a)
f_or_s=input('先攻：f,後攻：s')
game(f_or_s)


先攻：f,後攻：sf
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
your turn
00
0
2.0
2.0
[[0. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
your turn
0
1
1.0
1.0
[[0. 0. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
your turn
0
2
0.0
0.0
